### ISSUE TITLE
 java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams

### ISSUE THREAD

**Issue by StevenStarz** [okaybroda/ImageZoom#13]
11-23 16:40:50.623 17535-17535/compro.a99vr E/AndroidRuntime: FATAL EXCEPTION: main
                                                              Process: compro.a99vr, PID: 17535
                                                              java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                  at android.view.View.measure(View.java:17562)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                  at android.view.View.measure(View.java:17562)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                  at android.view.View.measure(View.java:17562)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                  at android.view.View.measure(View.java:17562)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                  at android.view.View.measure(View.java:17562)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                  at android.view.View.measure(View.java:17562)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                  at android.view.View.measure(View.java:17562)
                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5536)
                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2871)
                                                                  at android.view.View.measure(View.java:17562)
                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by StevenStarz** [comment]
I got this error when i try to random touch, like zoom in, out, double click, zoom and then drag, actually i don't know how to produce the bug, but sometimes got error by doing above action

**Comment by SureshSc** [comment]
I am experiencing same
