### ISSUE TITLE
I have a issue when render a bigger image.

### ISSUE THREAD

**Issue by prapagorn** [okaybroda/ImageZoom#8]
Your library is really good but It s crash when render a bigger image.

> AppCompatImageView not displayed because it is too large to fit into a software layer (or drawing cache), needs 10765440 bytes, only 8294400 available

> java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
>                                                                                        at android.graphics.Bitmap.createBitmap(Bitmap.java:773)
>                                                                                        at com.viven.imagezoom.ImageZoomHelper.onDispatchTouchEvent(ImageZoomHelper.java:106)

![original](https://user-images.githubusercontent.com/26864953/30016380-12f9aaf4-917f-11e7-8c82-69f9d4eac8ed.jpg)

**Comment by prapagorn** [comment]
#9 Closed by this PR
